/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignIn2RouteImport } from './routes/auth/sign-in-2'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthOtpRouteImport } from './routes/auth/otp'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as AppAuthenticatedRouteRouteImport } from './routes/app/_authenticated/route'
import { Route as AppAuthenticatedIndexRouteImport } from './routes/app/_authenticated/index'
import { Route as AppAuthenticatedSettingsRouteRouteImport } from './routes/app/_authenticated/settings/route'
import { Route as AppAuthenticatedUsersIndexRouteImport } from './routes/app/_authenticated/users/index'
import { Route as AppAuthenticatedTeamsIndexRouteImport } from './routes/app/_authenticated/teams/index'
import { Route as AppAuthenticatedTasksIndexRouteImport } from './routes/app/_authenticated/tasks/index'
import { Route as AppAuthenticatedSettingsIndexRouteImport } from './routes/app/_authenticated/settings/index'
import { Route as AppAuthenticatedHelpCenterIndexRouteImport } from './routes/app/_authenticated/help-center/index'
import { Route as AppAuthenticatedChatsIndexRouteImport } from './routes/app/_authenticated/chats/index'
import { Route as AppAuthenticatedAppsIndexRouteImport } from './routes/app/_authenticated/apps/index'
import { Route as AppAuthenticatedTeamsPlansRouteImport } from './routes/app/_authenticated/teams/plans'
import { Route as AppAuthenticatedSettingsSecurityRouteImport } from './routes/app/_authenticated/settings/security'
import { Route as AppAuthenticatedSettingsNotificationsRouteImport } from './routes/app/_authenticated/settings/notifications'
import { Route as AppAuthenticatedSettingsAppearanceRouteImport } from './routes/app/_authenticated/settings/appearance'
import { Route as AppAuthenticatedSettingsAccountRouteImport } from './routes/app/_authenticated/settings/account'
import { Route as AppAuthenticatedErrorsErrorRouteImport } from './routes/app/_authenticated/errors/$error'
import { Route as AppAuthenticatedAdminUsersIndexRouteImport } from './routes/app/_authenticated/admin/users/index'
import { Route as AppAuthenticatedAdminTeamsIndexRouteImport } from './routes/app/_authenticated/admin/teams/index'
import { Route as AppAuthenticatedAdminRolesIndexRouteImport } from './routes/app/_authenticated/admin/roles/index'
import { Route as AppAuthenticatedAdminBillingIndexRouteImport } from './routes/app/_authenticated/admin/billing/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignIn2Route = AuthSignIn2RouteImport.update({
  id: '/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedRouteRoute = AppAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthenticatedIndexRoute = AppAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthenticatedRouteRoute,
} as any)
const AppAuthenticatedSettingsRouteRoute =
  AppAuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedUsersIndexRoute =
  AppAuthenticatedUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedTeamsIndexRoute =
  AppAuthenticatedTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedTasksIndexRoute =
  AppAuthenticatedTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedSettingsIndexRoute =
  AppAuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthenticatedSettingsRouteRoute,
  } as any)
const AppAuthenticatedHelpCenterIndexRoute =
  AppAuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedChatsIndexRoute =
  AppAuthenticatedChatsIndexRouteImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAppsIndexRoute =
  AppAuthenticatedAppsIndexRouteImport.update({
    id: '/apps/',
    path: '/apps/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedTeamsPlansRoute =
  AppAuthenticatedTeamsPlansRouteImport.update({
    id: '/teams/plans',
    path: '/teams/plans',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedSettingsSecurityRoute =
  AppAuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AppAuthenticatedSettingsRouteRoute,
  } as any)
const AppAuthenticatedSettingsNotificationsRoute =
  AppAuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppAuthenticatedSettingsRouteRoute,
  } as any)
const AppAuthenticatedSettingsAppearanceRoute =
  AppAuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AppAuthenticatedSettingsRouteRoute,
  } as any)
const AppAuthenticatedSettingsAccountRoute =
  AppAuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AppAuthenticatedSettingsRouteRoute,
  } as any)
const AppAuthenticatedErrorsErrorRoute =
  AppAuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAdminUsersIndexRoute =
  AppAuthenticatedAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAdminTeamsIndexRoute =
  AppAuthenticatedAdminTeamsIndexRouteImport.update({
    id: '/admin/teams/',
    path: '/admin/teams/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAdminRolesIndexRoute =
  AppAuthenticatedAdminRolesIndexRouteImport.update({
    id: '/admin/roles/',
    path: '/admin/roles/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAdminBillingIndexRoute =
  AppAuthenticatedAdminBillingIndexRouteImport.update({
    id: '/admin/billing/',
    path: '/admin/billing/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppAuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-in-2': typeof AuthSignIn2Route
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app/settings': typeof AppAuthenticatedSettingsRouteRouteWithChildren
  '/app/': typeof AppAuthenticatedIndexRoute
  '/app/errors/$error': typeof AppAuthenticatedErrorsErrorRoute
  '/app/settings/account': typeof AppAuthenticatedSettingsAccountRoute
  '/app/settings/appearance': typeof AppAuthenticatedSettingsAppearanceRoute
  '/app/settings/notifications': typeof AppAuthenticatedSettingsNotificationsRoute
  '/app/settings/security': typeof AppAuthenticatedSettingsSecurityRoute
  '/app/teams/plans': typeof AppAuthenticatedTeamsPlansRoute
  '/app/apps/': typeof AppAuthenticatedAppsIndexRoute
  '/app/chats/': typeof AppAuthenticatedChatsIndexRoute
  '/app/help-center/': typeof AppAuthenticatedHelpCenterIndexRoute
  '/app/settings/': typeof AppAuthenticatedSettingsIndexRoute
  '/app/tasks/': typeof AppAuthenticatedTasksIndexRoute
  '/app/teams/': typeof AppAuthenticatedTeamsIndexRoute
  '/app/users/': typeof AppAuthenticatedUsersIndexRoute
  '/app/admin/billing/': typeof AppAuthenticatedAdminBillingIndexRoute
  '/app/admin/roles/': typeof AppAuthenticatedAdminRolesIndexRoute
  '/app/admin/teams/': typeof AppAuthenticatedAdminTeamsIndexRoute
  '/app/admin/users/': typeof AppAuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppAuthenticatedIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-in-2': typeof AuthSignIn2Route
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app/errors/$error': typeof AppAuthenticatedErrorsErrorRoute
  '/app/settings/account': typeof AppAuthenticatedSettingsAccountRoute
  '/app/settings/appearance': typeof AppAuthenticatedSettingsAppearanceRoute
  '/app/settings/notifications': typeof AppAuthenticatedSettingsNotificationsRoute
  '/app/settings/security': typeof AppAuthenticatedSettingsSecurityRoute
  '/app/teams/plans': typeof AppAuthenticatedTeamsPlansRoute
  '/app/apps': typeof AppAuthenticatedAppsIndexRoute
  '/app/chats': typeof AppAuthenticatedChatsIndexRoute
  '/app/help-center': typeof AppAuthenticatedHelpCenterIndexRoute
  '/app/settings': typeof AppAuthenticatedSettingsIndexRoute
  '/app/tasks': typeof AppAuthenticatedTasksIndexRoute
  '/app/teams': typeof AppAuthenticatedTeamsIndexRoute
  '/app/users': typeof AppAuthenticatedUsersIndexRoute
  '/app/admin/billing': typeof AppAuthenticatedAdminBillingIndexRoute
  '/app/admin/roles': typeof AppAuthenticatedAdminRolesIndexRoute
  '/app/admin/teams': typeof AppAuthenticatedAdminTeamsIndexRoute
  '/app/admin/users': typeof AppAuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/_authenticated': typeof AppAuthenticatedRouteRouteWithChildren
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-in-2': typeof AuthSignIn2Route
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app/_authenticated/settings': typeof AppAuthenticatedSettingsRouteRouteWithChildren
  '/app/_authenticated/': typeof AppAuthenticatedIndexRoute
  '/app/_authenticated/errors/$error': typeof AppAuthenticatedErrorsErrorRoute
  '/app/_authenticated/settings/account': typeof AppAuthenticatedSettingsAccountRoute
  '/app/_authenticated/settings/appearance': typeof AppAuthenticatedSettingsAppearanceRoute
  '/app/_authenticated/settings/notifications': typeof AppAuthenticatedSettingsNotificationsRoute
  '/app/_authenticated/settings/security': typeof AppAuthenticatedSettingsSecurityRoute
  '/app/_authenticated/teams/plans': typeof AppAuthenticatedTeamsPlansRoute
  '/app/_authenticated/apps/': typeof AppAuthenticatedAppsIndexRoute
  '/app/_authenticated/chats/': typeof AppAuthenticatedChatsIndexRoute
  '/app/_authenticated/help-center/': typeof AppAuthenticatedHelpCenterIndexRoute
  '/app/_authenticated/settings/': typeof AppAuthenticatedSettingsIndexRoute
  '/app/_authenticated/tasks/': typeof AppAuthenticatedTasksIndexRoute
  '/app/_authenticated/teams/': typeof AppAuthenticatedTeamsIndexRoute
  '/app/_authenticated/users/': typeof AppAuthenticatedUsersIndexRoute
  '/app/_authenticated/admin/billing/': typeof AppAuthenticatedAdminBillingIndexRoute
  '/app/_authenticated/admin/roles/': typeof AppAuthenticatedAdminRolesIndexRoute
  '/app/_authenticated/admin/teams/': typeof AppAuthenticatedAdminTeamsIndexRoute
  '/app/_authenticated/admin/users/': typeof AppAuthenticatedAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/auth/forgot-password'
    | '/auth/otp'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-in-2'
    | '/auth/sign-up'
    | '/app/settings'
    | '/app/'
    | '/app/errors/$error'
    | '/app/settings/account'
    | '/app/settings/appearance'
    | '/app/settings/notifications'
    | '/app/settings/security'
    | '/app/teams/plans'
    | '/app/apps/'
    | '/app/chats/'
    | '/app/help-center/'
    | '/app/settings/'
    | '/app/tasks/'
    | '/app/teams/'
    | '/app/users/'
    | '/app/admin/billing/'
    | '/app/admin/roles/'
    | '/app/admin/teams/'
    | '/app/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/auth/forgot-password'
    | '/auth/otp'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-in-2'
    | '/auth/sign-up'
    | '/app/errors/$error'
    | '/app/settings/account'
    | '/app/settings/appearance'
    | '/app/settings/notifications'
    | '/app/settings/security'
    | '/app/teams/plans'
    | '/app/apps'
    | '/app/chats'
    | '/app/help-center'
    | '/app/settings'
    | '/app/tasks'
    | '/app/teams'
    | '/app/users'
    | '/app/admin/billing'
    | '/app/admin/roles'
    | '/app/admin/teams'
    | '/app/admin/users'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/_authenticated'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/auth/forgot-password'
    | '/auth/otp'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-in-2'
    | '/auth/sign-up'
    | '/app/_authenticated/settings'
    | '/app/_authenticated/'
    | '/app/_authenticated/errors/$error'
    | '/app/_authenticated/settings/account'
    | '/app/_authenticated/settings/appearance'
    | '/app/_authenticated/settings/notifications'
    | '/app/_authenticated/settings/security'
    | '/app/_authenticated/teams/plans'
    | '/app/_authenticated/apps/'
    | '/app/_authenticated/chats/'
    | '/app/_authenticated/help-center/'
    | '/app/_authenticated/settings/'
    | '/app/_authenticated/tasks/'
    | '/app/_authenticated/teams/'
    | '/app/_authenticated/users/'
    | '/app/_authenticated/admin/billing/'
    | '/app/_authenticated/admin/roles/'
    | '/app/_authenticated/admin/teams/'
    | '/app/_authenticated/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in-2': {
      id: '/auth/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/auth/sign-in-2'
      preLoaderRoute: typeof AuthSignIn2RouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated': {
      id: '/app/_authenticated'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthenticatedRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/_authenticated/': {
      id: '/app/_authenticated/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAuthenticatedIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/settings': {
      id: '/app/_authenticated/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppAuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/users/': {
      id: '/app/_authenticated/users/'
      path: '/users'
      fullPath: '/app/users/'
      preLoaderRoute: typeof AppAuthenticatedUsersIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/teams/': {
      id: '/app/_authenticated/teams/'
      path: '/teams'
      fullPath: '/app/teams/'
      preLoaderRoute: typeof AppAuthenticatedTeamsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/tasks/': {
      id: '/app/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/app/tasks/'
      preLoaderRoute: typeof AppAuthenticatedTasksIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/settings/': {
      id: '/app/_authenticated/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppAuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AppAuthenticatedSettingsRouteRoute
    }
    '/app/_authenticated/help-center/': {
      id: '/app/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/app/help-center/'
      preLoaderRoute: typeof AppAuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/chats/': {
      id: '/app/_authenticated/chats/'
      path: '/chats'
      fullPath: '/app/chats/'
      preLoaderRoute: typeof AppAuthenticatedChatsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/apps/': {
      id: '/app/_authenticated/apps/'
      path: '/apps'
      fullPath: '/app/apps/'
      preLoaderRoute: typeof AppAuthenticatedAppsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/teams/plans': {
      id: '/app/_authenticated/teams/plans'
      path: '/teams/plans'
      fullPath: '/app/teams/plans'
      preLoaderRoute: typeof AppAuthenticatedTeamsPlansRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/settings/security': {
      id: '/app/_authenticated/settings/security'
      path: '/security'
      fullPath: '/app/settings/security'
      preLoaderRoute: typeof AppAuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AppAuthenticatedSettingsRouteRoute
    }
    '/app/_authenticated/settings/notifications': {
      id: '/app/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AppAuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AppAuthenticatedSettingsRouteRoute
    }
    '/app/_authenticated/settings/appearance': {
      id: '/app/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/app/settings/appearance'
      preLoaderRoute: typeof AppAuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AppAuthenticatedSettingsRouteRoute
    }
    '/app/_authenticated/settings/account': {
      id: '/app/_authenticated/settings/account'
      path: '/account'
      fullPath: '/app/settings/account'
      preLoaderRoute: typeof AppAuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AppAuthenticatedSettingsRouteRoute
    }
    '/app/_authenticated/errors/$error': {
      id: '/app/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/app/errors/$error'
      preLoaderRoute: typeof AppAuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/admin/users/': {
      id: '/app/_authenticated/admin/users/'
      path: '/admin/users'
      fullPath: '/app/admin/users/'
      preLoaderRoute: typeof AppAuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/admin/teams/': {
      id: '/app/_authenticated/admin/teams/'
      path: '/admin/teams'
      fullPath: '/app/admin/teams/'
      preLoaderRoute: typeof AppAuthenticatedAdminTeamsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/admin/roles/': {
      id: '/app/_authenticated/admin/roles/'
      path: '/admin/roles'
      fullPath: '/app/admin/roles/'
      preLoaderRoute: typeof AppAuthenticatedAdminRolesIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/admin/billing/': {
      id: '/app/_authenticated/admin/billing/'
      path: '/admin/billing'
      fullPath: '/app/admin/billing/'
      preLoaderRoute: typeof AppAuthenticatedAdminBillingIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
  }
}

interface AppAuthenticatedSettingsRouteRouteChildren {
  AppAuthenticatedSettingsAccountRoute: typeof AppAuthenticatedSettingsAccountRoute
  AppAuthenticatedSettingsAppearanceRoute: typeof AppAuthenticatedSettingsAppearanceRoute
  AppAuthenticatedSettingsNotificationsRoute: typeof AppAuthenticatedSettingsNotificationsRoute
  AppAuthenticatedSettingsSecurityRoute: typeof AppAuthenticatedSettingsSecurityRoute
  AppAuthenticatedSettingsIndexRoute: typeof AppAuthenticatedSettingsIndexRoute
}

const AppAuthenticatedSettingsRouteRouteChildren: AppAuthenticatedSettingsRouteRouteChildren =
  {
    AppAuthenticatedSettingsAccountRoute: AppAuthenticatedSettingsAccountRoute,
    AppAuthenticatedSettingsAppearanceRoute:
      AppAuthenticatedSettingsAppearanceRoute,
    AppAuthenticatedSettingsNotificationsRoute:
      AppAuthenticatedSettingsNotificationsRoute,
    AppAuthenticatedSettingsSecurityRoute:
      AppAuthenticatedSettingsSecurityRoute,
    AppAuthenticatedSettingsIndexRoute: AppAuthenticatedSettingsIndexRoute,
  }

const AppAuthenticatedSettingsRouteRouteWithChildren =
  AppAuthenticatedSettingsRouteRoute._addFileChildren(
    AppAuthenticatedSettingsRouteRouteChildren,
  )

interface AppAuthenticatedRouteRouteChildren {
  AppAuthenticatedSettingsRouteRoute: typeof AppAuthenticatedSettingsRouteRouteWithChildren
  AppAuthenticatedIndexRoute: typeof AppAuthenticatedIndexRoute
  AppAuthenticatedErrorsErrorRoute: typeof AppAuthenticatedErrorsErrorRoute
  AppAuthenticatedTeamsPlansRoute: typeof AppAuthenticatedTeamsPlansRoute
  AppAuthenticatedAppsIndexRoute: typeof AppAuthenticatedAppsIndexRoute
  AppAuthenticatedChatsIndexRoute: typeof AppAuthenticatedChatsIndexRoute
  AppAuthenticatedHelpCenterIndexRoute: typeof AppAuthenticatedHelpCenterIndexRoute
  AppAuthenticatedTasksIndexRoute: typeof AppAuthenticatedTasksIndexRoute
  AppAuthenticatedTeamsIndexRoute: typeof AppAuthenticatedTeamsIndexRoute
  AppAuthenticatedUsersIndexRoute: typeof AppAuthenticatedUsersIndexRoute
  AppAuthenticatedAdminBillingIndexRoute: typeof AppAuthenticatedAdminBillingIndexRoute
  AppAuthenticatedAdminRolesIndexRoute: typeof AppAuthenticatedAdminRolesIndexRoute
  AppAuthenticatedAdminTeamsIndexRoute: typeof AppAuthenticatedAdminTeamsIndexRoute
  AppAuthenticatedAdminUsersIndexRoute: typeof AppAuthenticatedAdminUsersIndexRoute
}

const AppAuthenticatedRouteRouteChildren: AppAuthenticatedRouteRouteChildren = {
  AppAuthenticatedSettingsRouteRoute:
    AppAuthenticatedSettingsRouteRouteWithChildren,
  AppAuthenticatedIndexRoute: AppAuthenticatedIndexRoute,
  AppAuthenticatedErrorsErrorRoute: AppAuthenticatedErrorsErrorRoute,
  AppAuthenticatedTeamsPlansRoute: AppAuthenticatedTeamsPlansRoute,
  AppAuthenticatedAppsIndexRoute: AppAuthenticatedAppsIndexRoute,
  AppAuthenticatedChatsIndexRoute: AppAuthenticatedChatsIndexRoute,
  AppAuthenticatedHelpCenterIndexRoute: AppAuthenticatedHelpCenterIndexRoute,
  AppAuthenticatedTasksIndexRoute: AppAuthenticatedTasksIndexRoute,
  AppAuthenticatedTeamsIndexRoute: AppAuthenticatedTeamsIndexRoute,
  AppAuthenticatedUsersIndexRoute: AppAuthenticatedUsersIndexRoute,
  AppAuthenticatedAdminBillingIndexRoute:
    AppAuthenticatedAdminBillingIndexRoute,
  AppAuthenticatedAdminRolesIndexRoute: AppAuthenticatedAdminRolesIndexRoute,
  AppAuthenticatedAdminTeamsIndexRoute: AppAuthenticatedAdminTeamsIndexRoute,
  AppAuthenticatedAdminUsersIndexRoute: AppAuthenticatedAdminUsersIndexRoute,
}

const AppAuthenticatedRouteRouteWithChildren =
  AppAuthenticatedRouteRoute._addFileChildren(
    AppAuthenticatedRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppAuthenticatedRouteRoute: typeof AppAuthenticatedRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuthenticatedRouteRoute: AppAuthenticatedRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignIn2Route: typeof AuthSignIn2Route
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignIn2Route: AuthSignIn2Route,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
